name: flow_matching
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda
  - torchvision
  - matplotlib
  - jupyter
  - numpy
  - pip
  - tqdm
  - pip:
    - ipykernel
    - torchdiffeq
    - scikit-learn
    - submitit
    - torchmetrics[image]
    - transformers
